name: deploy

on:
  push:
    branches:
      - main
# on:
#   push:
#     tags:
#       - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Deploy
        uses: ./.github/actions/deploy-action
        with:
          version: v1.0.0
          namespace: "stage"
