name: deploy

on:
  push:
    branches:
      - main
# on:
#   push:
#     tags:
#       - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: ./template
        with:
          version: v1.0.0
          namespace: "stage"
